FROM mbopm/docker-dind-alpine-healthcheck:29.1.3-dind-alpine3.23
LABEL org.opencontainers.image.authors="outrage_breath.0t@icloud.com"
WORKDIR /workdir
RUN apk add --no-cache openjdk21-jdk bash
ENTRYPOINT []
VOLUME /workdir
