FROM mbopm/docker-dind-alpine-healthcheck:29.6.1-dind-alpine3.24
LABEL org.opencontainers.image.authors="outrage_breath.0t@icloud.com"
WORKDIR /workdir
RUN apk add --no-cache openjdk21-jdk bash
ENTRYPOINT []
VOLUME /workdir
