services:

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    hostname: postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - db:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: s3cr3t
      TZ: UTC
      PGTZ: UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 1s
      timeout: 2s
      retries: 10

  mail:
    image: axllent/mailpit:v1.28
    container_name: mail
    hostname: mail
    ports:
      - "127.0.0.1:8025:8025" # ui
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./auth:/auth:ro
      - mail:/data:rw
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_UI_AUTH_FILE: /auth
      MP_SMTP_AUTH_FILE: /auth
      MP_SMTP_DISABLE_RDNS: true
      TZ: UTC
    healthcheck:
      test: wget --spider --tries 1 http://smtp:pass123@localhost:8025
      interval: 1s
      timeout: 1s
      retries: 5

  moodle:
#    build: .
    image: mbopm/moodle:latest
    hostname: moodle
    container_name: moodle
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      postgres:
        condition: service_healthy
      mail:
        condition: service_healthy
    volumes:
      - moodle_data:/data:rw

volumes:
  db:
  mail:
  moodle_data:
